name: gutils37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cc-plugin-glider=1.0.6
  - certifi=2019.3.9
  - cf-units=2.1.1
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - compliance-checker=4.2.2
  - cryptography=2.7
  - curl=7.64.1
  - decorator=4.4.0
  - entrypoints=0.3
  - expat=2.2.5
  - flake8=3.7.7
  - geos=3.7.1
  - gsw=3.3.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=58.2
  - idna=2.8
  - importlib_metadata=0.18
  - ipdb=0.12
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - isodate=0.6.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libxslt=1.1.32
  - lxml=4.3.4
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - more-itertools=4.3.0
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - numpy=1.16.4
  - openblas=0.3.5
  - openssl=1.1.1b
  - owslib=0.17.1
  - packaging=19.0
  - pandas=0.24.2
  - parso=0.4.0
  - pendulum=2.0.4
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - pluggy=0.12.0
  - pocean-core=1.7.0
  - proj4=6.1.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pygc=1.2.1
  - pygeoif=0.7
  - pygments=2.4.2
  - pyinotify=0.9.6
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=2.2.0
  - pysocks=1.7.0
  - pytest=4.6.3
  - pytest-flake8=1.0.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pytzdata=2019.1
  - readline=7.0
  - regex=2019.06.08
  - requests=2.22.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - simplejson=3.16.0
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.9
  - traitlets=4.3.2
  - udunits2=2.2.27.6
  - urllib3=1.24.3
  - wcwidth=0.1.7
  - wheel=0.33.4
  - whichcraft=0.5.2
  - xz=5.2.4
  - zipp=0.5.1
  - zlib=1.2.11
