name: gutils37
channels:
  - conda-forge
  - axiom-data-science
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - antlr-python-runtime=4.7.2
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - cc-plugin-glider=2.0.0
  - certifi=2019.6.16
  - cf-units=2.1.3
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - compliance-checker=4.2.2
  - cryptography=2.7
  - curl=7.65.3
  - decorator=4.4.0
  - entrypoints=0.3
  - expat=2.2.5
  - flake8=3.7.8
  - geos=3.7.2
  - gsw=3.3.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.8
  - importlib_metadata=0.21
  - ipdb=0.12.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - isodate=0.6.0
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9c
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.1
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - more-itertools=7.2.0
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - numpy=1.17.2
  - openssl=1.1.1c
  - owslib=0.18.0
  - packaging=19.0
  - pandas=0.24.2
  - parso=0.5.1
  - pendulum=2.0.5
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - pluggy=0.13.0
  - pocean-core=1.9.0
  - proj4=6.1.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pygc=1.2.1
  - pygeoif=0.7
  - pygments=2.4.2
  - pyinotify=0.9.6
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyproj=2.3.1
  - pysocks=1.7.0
  - pytest=5.1.2
  - pytest-flake8=1.0.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pytzdata=2019.2
  - readline=8.0
  - regex=2019.08.19
  - requests=2.22.0
  - scipy=1.3.1
  - setuptools=41.2.0
  - shapely=1.6.4
  - simplejson=3.16.0
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.9
  - traitlets=4.3.2
  - udunits2=2.2.27.6
  - urllib3=1.25.3
  - wcwidth=0.1.7
  - wheel=0.33.6
  - whichcraft=0.6.1
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
